org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8
org.gradle.daemon=false

mod_id=apothic_enchanting_terminal
mod_name=Apothic Enchanting Terminal
mod_group=com.example.apothicenchantingterminal
mod_version=0.1.0

minecraft_version=1.21.1
neo_version=21.1.244
ae2_version=19.2.18
guideme_version=21.1.1
apothic_enchanting_version=1.21.1-1.6.3
placebo_version=1.21.1-9.9.0
apothic_attributes_version=1.21.1-2.4.0
ae2wtlib_version=19.5.1
