modLoader="javafml"
loaderVersion="[1,)"
license="MIT"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
description='''
Opens an Apothic Enchanting library through an AE2 network, using a terminal block and a portable terminal.
'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.244,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="ae2"
    type="required"
    versionRange="[19,20)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="apothic_enchanting"
    type="required"
    versionRange="[1.6.0,2)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="ae2wtlib"
    type="optional"
    versionRange="[19.5,)"
    ordering="AFTER"
    side="BOTH"
